# docker-compose.yml
version: "2"
services:
  api_frioaereo:
    container_name: api_frioaereo
      #    image: api_frioaereo:1.0
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py
    volumes:
      - /usr/local/volumes/fileserver/:/app/fileserver/
    ports:
      - "9886:9886"