# docker-compose.yml
version: "2"
services:
  api_cuidappte:
    container_name: api_g4s
    image: api_g4s:1.0
    # build: .
    command: python3 main.py
    volumes:
      - /usr/local/volumes/fileserver/:/app/fileserver/
    ports:
      - "9877:9877"