# docker-compose.yml
version: "2"
services:
  api_tcomp:
    container_name: api_tcomp
#    image: api_tcomp:1.0
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py
    volumes:
      - /usr/local/volumes/fileserver/:/app/fileserver/
    ports:
      - "9879:9879"