# docker-compose.yml
version: "2"
services:
  api_cuidappte_laprotectora:
    container_name: api_cuidappte_laprotectora
    #    image: api_cuidappte_laprotectora:1.0
    # build: .
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py
    volumes:
      - /usr/local/volumes/fileserver/:/app/fileserver/
    ports:
      - "9889:9889"